apiVersion: apps/v1
kind: Deployment
metadata:
  name: animated-car-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: animated-car
  template:
    metadata:
      labels:
        app: animated-car
    spec:
      containers:
        - name: animated-car
          image: yash5090/animated-car:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
